### ISSUE TITLE
Some *.npy cannot be read

### ISSUE THREAD

**Issue by AlexFEBo** [bsse-scf/pyMINFLUX#11]
**Describe the bug**
With the version 0.4.0, some *.npy file cannot be read:
Loading the file the _via_ the load button or  by dragging does not load the data.
The console shows: Reloaded default settings.
The file can loaded in pyMINFLUX 0.3.0

**To Reproduce**
One of the files that cannot be loaded was sent to the authors

**Expected behavior**
I would expect the localisation to be displayed in the Data Plotter window

**Screenshots**
Screenshot of the file opened with pyMINFLUX 0.3.0 vs pyMINFLUX 0.4.0

**Environment (please complete the following information):**
 - OS: Windows
 - OS details: Windows 11 Enterprise
 - Version [e.g. 0.4.0]
 - Distribution [pre-pakaged app]
<img width="1919" alt="pyMINFLUX" src="https://github.com/bsse-scf/pyMINFLUX/assets/75954405/5866fb11-80cd-4df4-ae50-fab06e2b45da">

**Comment by aarpon** [comment]
Fixed in upcoming 0.4.1.
