### ISSUE TITLE
Change of the default directory for exporting plots

### ISSUE THREAD

**Issue by AlexFEBo** [bsse-scf/pyMINFLUX#12]
**What new features would you like to see implemented?**
The default directory for exporting plots would correspond to the directory from which the dataset was opened (instead of pyMINFLUX

**Can you provide some motivation for why this feature should be added?**
That would save time instead of having to navigate back to the intended folder for every plot to export

**Comment by aarpon** [comment]
Implemented in https://github.com/bsse-scf/pyMINFLUX/commit/db195f815b27eadc67ce43e22d2b4810e7f2d00f.
