### ISSUE TITLE
Export all the plots at once

### ISSUE THREAD

**Issue by AlexFEBo** [bsse-scf/pyMINFLUX#13]
**What new features would you like to see implemented?**
Adding the possibility to export all the plots from EFO thresholding / CFR thresholding at once (instead of exporting them one by one)

**Can you provide some motivation for why this feature should be added?**
Save time for exporting and comparing data between experiments

**Comment by aarpon** [comment]
Fixed in commit 98fec1c475ddf4e7c3a3bad048fad06e358ca7d7.
