### ISSUE TITLE
Implement Fourier Ring Correlation calculation and trending display

### ISSUE THREAD

**Issue by javicasarias** [bsse-scf/pyMINFLUX#2]
**What new features would you like to see implemented?**
Implement [Fourier Ring Correlation (FRC) calculation](https://www.nature.com/articles/nmeth.2448) and trend plotting.

**Can you provide some motivation for why this feature should be added?**
The progression of the FRC resolution has been previously used in the [literature](https://www.nature.com/articles/s41592-022-01577-1) as abort criterion to determine the endpoint of MINFLUX measurements.

**Describe the solution you'd like**
Having an additional option in the Time Inspector drop-down menu to plot the FRC resolution over the course of the acquisition.

**Comment by aarpon** [comment]
Implemented in version 0.2.0.
