### ISSUE TITLE
Implementation of trace statistics window

### ISSUE THREAD

**Issue by javicasarias** [bsse-scf/pyMINFLUX#4]
**What new features would you like to see implemented?**
The addition of a new window showing the distribution of number of localizations per trace.

**Can you provide some motivation for why this feature should be added?**
Being able to quickly assess how many localizations are achieved for each fluorophore activation would be useful to assess the compatibility of the MINFLUX sequence to the blinking dynamics.

**Describe the solution you'd like**
Addition of a new window plotting the histogram of the number of localizations per trace, with some statistics for the entire dataset if possible (such as median value).

**Comment by aarpon** [comment]
Implemented in release 0.3.0.
