### ISSUE TITLE
Paraview pyminflux_reader.py

### ISSUE THREAD

**Issue by Charlotte1001** [bsse-scf/pyMINFLUX#5]
**Describe the bug**
I downloaded the pyminflux_reader.py and followed the installation procedure that you describe to install it
in Paraview. When I load the plugin I obtain an error message. See the screenshot below:

**Environment (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 22H2
 - Python version 3.11.6

![ErrorMessagePluginLoadParaview](https://github.com/bsse-scf/pyMINFLUX/assets/28453697/536049c7-f766-4954-aa19-a7b09f4d3d7f)

**Comment by aarpon** [comment]
ParaView bundles Python 3.9, so it is strange that the error complains about Python being version 3.11.6. It looks like the plugin is not being run by ParaView itself but externally, by another Python interpreter. Are you opening the `.npy` file from the `File > Open` menu in ParaView? Have you followed all installation steps on https://github.com/bsse-scf/pyMINFLUX/wiki/pyMINFLUX-user-manual#3d-data-viewer?

**Comment by Charlotte1001** [comment]
I followed the instruction: "For 3D data visualization, pyMINFLUX offers a [ParaView](https://www.paraview.org/) plug-in (the Data Plotter is 2D only). You can download it from [here](https://raw.githubusercontent.com/bsse-scf/pyMINFLUX/master/paraview_plugins/pyminflux_reader.py). To install it, select Manage Plugins... from ParaView's Tools menu, click on Load New... (Image 2, A)" and the error message pops up when I want to load the plugin in Paraview.

FYI: After the installation of the plugin under Windows failed, I tryed the installation of the plugin on macOS Ventura 13.5.2 with a python verison of 3.9.13 and Paraview v5.11.2. Everything went smoothly and I could open the .pmx data file that I saved in pyMINFLUX in Paraview and it got properly displayed.

If possible, I would also like to run it on my Windows machine.

**Comment by aarpon** [comment]
Could I ask you to do two things for me?

1. Could you please select `Help > About` in ParaView, then click on the button `Copy to Clipboard` at the bottom left corner of the dialog, and paste the client information here? 
2. To make sure that the download of `pyminflux_reader.py` did not damage the file in some way, could you please copy-paste the content of your `C:\Users\ckaplan\Documents\pyminflux_reader.py` here as well?

Thanks!

**Comment by aarpon** [comment]
Would it be possible for you to upgrade ParaView to version 5.11.2 from https://www.paraview.org/download/ also for Windows? The plug-in indeed does not work with older versions of ParaView.
