### ISSUE TITLE
Add support for custom MINFLUX sequences

### ISSUE THREAD

**Issue by javicasarias** [bsse-scf/pyMINFLUX#6]
**What new features would you like to see implemented?**
An easy way to select from which iteration the different MINFLUX variables are extracted to build the pyMINFLUX dataframe.

**Can you provide some motivation for why this feature should be added?**
This would allow to import a wider variety of data into pyMINFLUX, and also to inspect the metrics for earlier iterations for troubleshooting.

**Describe the solution you'd like**
When opening a file, a dialog would allow to freely select the source for each MINFLUX variable (similar to the Bio-Formats importer dialog on Fiji)

**Comment by javicasarias** [comment]
On 0.3, dwell time is hard-coded to be 1 ms, this should be made an option on the importer

**Comment by aarpon** [comment]
Dwell time is now a parameter to be set when loading the file.

**Comment by aarpon** [comment]
Initial support for custom sequences is implemented.

**Comment by aarpon** [comment]
Completed and to be released wity pyMINFLUX 0.4.0.
