### ISSUE TITLE
Implement free-text selection of the ROI on the Time Inspector

### ISSUE THREAD

**Issue by javicasarias** [bsse-scf/pyMINFLUX#7]
**What new features would you like to see implemented?**
Add the right-click menu present on other parts of the software (like the analyser) to the Time Inspector, specially the "Set ROI ranges" option.

**Can you provide some motivation for why this feature should be added?**
This would allow to consistently subtract a given amount of minutes from multiple datasets.

**Comment by aarpon** [comment]
Completed and to be released wity pyMINFLUX 0.4.0.
