### ISSUE TITLE
Add support for single-molecule tracking datasets

### ISSUE THREAD

**Issue by javicasarias** [bsse-scf/pyMINFLUX#8]
**What new features would you like to see implemented?**
Add support for single-molecule tracking datasets.

**Can you provide some motivation for why this feature should be added?**
To date, only measurements acquired in localisation mode are compatible with pyMINFLUX.

**Describe the solution you'd like**
After the loaded file has been identified as a tracking dataset, visualization options and trace statistics can be adjusted to better reflect the nature of the data. For instance, localisations belonging to the same track could be connected by a line, and additional statistics, such as temporal resolution, could be provided.

**Comment by javicasarias** [comment]
The following current functionalities would not apply for this kind of dataset:

1. Localisation precision plotting on the Analyser window
2. Localisation precision per minute option on the Time Inspector
3. Option for plotting average localisation per trace on the Data Plotter
4. FRC Analyser under the Analysis menu

Instead, the following metrics should be considered:

1. Time between subsequent measurements within the same trace (temporal resolution) - To be added to the Analyser as histogram with median value
2. Distance/speed between subsequent measurements within the same trace - To be added to the Analyser as histogram with median value
3. Total distance covered per trace - To be added to the Analyser as histogram with median value

**Comment by aarpon** [comment]
Changes so far:

**Functionalities not fitting to tracking datasets**:

* ~~Localisation precision plotting on the Analyser window~~: **✓** _(replaced by new tracking-specific metrics and plots, see section below)_
* Localisation precision per minute option on the Time Inspector: still to do
* Option for plotting average localisation per trace on the Data Plotter: still to do
* ~~FRC Analyser under the Analysis menu~~: **✓** _(disabled for tracking datasets)_

**New metrics for tracking datasets**:

The following metrics were added to the Analyzers for tracking datasets as replacements for the localization precision plots. Each metric is displayed as histogram with lines depicting the median value and the inter-quartile range; the label for the median also displays the median absolute deviation:

* ~~Time between subsequent measurements within the same trace (temporal resolution)~~: **✓**
* ~~Distance/speed between subsequent measurements within the same trace~~: **✓ (distance)**
* ~~Total distance covered per trace~~: **✓**

**Comment by aarpon** [comment]
Completed and to be released wity pyMINFLUX 0.4.0.
